#include "structured_light/point_cloud_process.hpp"

#include <pcl/filters/filter.h>
#include <pcl/filters/passthrough.h>
#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/io/pcd_io.h>
#include <pcl/io/ply_io.h>

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <stdexcept>
#include <string>
#include <vector>

namespace sl3d
{
namespace
{

std::string GetLowerExtension(const std::string& file_path)
{
  std::string extension = std::filesystem::path(file_path).extension().string();

  std::transform(extension.begin(), extension.end(), extension.begin(), [](unsigned char character)
                 { return static_cast<char>(std::tolower(character)); });

  return extension;
}

void EnsureParentDirectory(const std::string& file_path)
{
  const std::filesystem::path path = file_path;

  if (!path.parent_path().empty())
  {
    std::filesystem::create_directories(path.parent_path());
  }
}

int SavePlyAscii(const std::string& file_path, const PointCloud& cloud)
{
  std::ofstream output(file_path);

  if (!output.is_open())
  {
    return -1;
  }

  output << "ply\n"
         << "format ascii 1.0\n"
         << "comment generated by structured-light-3d-reconstruction\n"
         << "element vertex " << cloud.size() << '\n'
         << "property float x\n"
         << "property float y\n"
         << "property float z\n"
         << "end_header\n";

  output << std::fixed << std::setprecision(7);

  for (const auto& point : cloud)
  {
    output << point.x << ' ' << point.y << ' ' << point.z << '\n';
  }

  return output.good() ? 0 : -1;
}

void WriteFloatLittleEndian(std::ostream& output, float value)
{
  static_assert(sizeof(float) == sizeof(std::uint32_t), "This PLY writer requires 32-bit float.");

  std::uint32_t bits = 0;

  std::memcpy(&bits, &value, sizeof(float));

  const unsigned char bytes[4] = {static_cast<unsigned char>(bits & 0xFFU),

                                  static_cast<unsigned char>((bits >> 8U) & 0xFFU),

                                  static_cast<unsigned char>((bits >> 16U) & 0xFFU),

                                  static_cast<unsigned char>((bits >> 24U) & 0xFFU)};

  output.write(reinterpret_cast<const char*>(bytes), sizeof(bytes));
}

int SavePlyBinary(const std::string& file_path, const PointCloud& cloud)
{
  std::ofstream output(file_path, std::ios::binary);

  if (!output.is_open())
  {
    return -1;
  }

  output << "ply\n"
         << "format binary_little_endian 1.0\n"
         << "comment generated by structured-light-3d-reconstruction\n"
         << "element vertex " << cloud.size() << '\n'
         << "property float x\n"
         << "property float y\n"
         << "property float z\n"
         << "end_header\n";

  for (const auto& point : cloud)
  {
    WriteFloatLittleEndian(output, point.x);

    WriteFloatLittleEndian(output, point.y);

    WriteFloatLittleEndian(output, point.z);
  }

  return output.good() ? 0 : -1;
}

void ValidateProcessingOptions(const PointCloudProcessingOptions& options)
{
  if (options.pass_through.enabled)
  {
    if (options.pass_through.axis != "x" && options.pass_through.axis != "y" &&
        options.pass_through.axis != "z")
    {
      throw std::invalid_argument("PassThrough axis must be x, y, or z.");
    }

    if (!std::isfinite(options.pass_through.min_limit) ||
        !std::isfinite(options.pass_through.max_limit) ||
        options.pass_through.min_limit >= options.pass_through.max_limit)
    {
      throw std::invalid_argument("Invalid PassThrough limits.");
    }
  }

  if (options.statistical_outlier.enabled)
  {
    if (options.statistical_outlier.mean_k <= 0)
    {
      throw std::invalid_argument("StatisticalOutlier mean_k must be positive.");
    }

    if (!std::isfinite(options.statistical_outlier.stddev_mul) ||
        options.statistical_outlier.stddev_mul <= 0.0)
    {
      throw std::invalid_argument("StatisticalOutlier stddev_mul must be positive.");
    }
  }

  if (options.voxel_grid.enabled)
  {
    if (!std::isfinite(options.voxel_grid.leaf_size) || options.voxel_grid.leaf_size <= 0.0F)
    {
      throw std::invalid_argument("VoxelGrid leaf_size must be positive.");
    }
  }
}

}  // namespace

PointCloud::Ptr ConvertTriangulationResultToPointCloud(
    const TriangulationResult& triangulation_result)
{
  if (triangulation_result.points_3d.empty() || triangulation_result.valid_mask.empty())
  {
    throw std::invalid_argument("Triangulation result must not be empty.");
  }

  if (triangulation_result.points_3d.size() != triangulation_result.valid_mask.size())
  {
    throw std::invalid_argument("3D points and valid mask sizes must match.");
  }

  if (triangulation_result.points_3d.type() != CV_64FC3)
  {
    throw std::invalid_argument("Triangulation points must be CV_64FC3.");
  }

  if (triangulation_result.valid_mask.type() != CV_8UC1)
  {
    throw std::invalid_argument("Triangulation valid mask must be CV_8UC1.");
  }

  PointCloud::Ptr cloud(new PointCloud);

  cloud->reserve(triangulation_result.point_count);

  for (int y = 0; y < triangulation_result.points_3d.rows; ++y)
  {
    for (int x = 0; x < triangulation_result.points_3d.cols; ++x)
    {
      if (triangulation_result.valid_mask.at<unsigned char>(y, x) == 0)
      {
        continue;
      }

      const cv::Vec3d point = triangulation_result.points_3d.at<cv::Vec3d>(y, x);

      if (!std::isfinite(point[0]) || !std::isfinite(point[1]) || !std::isfinite(point[2]))
      {
        continue;
      }

      cloud->emplace_back(static_cast<float>(point[0]), static_cast<float>(point[1]),
                          static_cast<float>(point[2]));
    }
  }

  cloud->width = static_cast<std::uint32_t>(cloud->size());

  cloud->height = 1;

  cloud->is_dense = true;

  return cloud;
}

PointCloud::Ptr LoadPointCloud(const std::string& file_path)
{
  const std::string extension = GetLowerExtension(file_path);

  PointCloud::Ptr cloud(new PointCloud);

  int status = -1;

  if (extension == ".ply")
  {
    status = pcl::io::loadPLYFile<pcl::PointXYZ>(file_path, *cloud);
  }
  else if (extension == ".pcd")
  {
    status = pcl::io::loadPCDFile<pcl::PointXYZ>(file_path, *cloud);
  }
  else
  {
    throw std::invalid_argument("Point cloud input must be .ply or .pcd.");
  }

  if (status < 0)
  {
    throw std::runtime_error("Failed to load point cloud: " + file_path);
  }

  return cloud;
}

void SavePointCloud(const std::string& file_path, const PointCloud& cloud, bool binary)
{
  if (cloud.empty())
  {
    throw std::invalid_argument("Cannot save an empty point cloud.");
  }

  const std::string extension = GetLowerExtension(file_path);

  if (extension != ".ply" && extension != ".pcd")
  {
    throw std::invalid_argument("Point cloud output must use .ply or .pcd extension.");
  }

  EnsureParentDirectory(file_path);

  int status = -1;

  if (extension == ".ply")
  {
    status = binary ? SavePlyBinary(file_path, cloud) : SavePlyAscii(file_path, cloud);
  }
  else
  {
    status = binary ? pcl::io::savePCDFileBinary(file_path, cloud)
                    : pcl::io::savePCDFileASCII(file_path, cloud);
  }

  if (status < 0)
  {
    throw std::runtime_error("Failed to save point cloud: " + file_path);
  }
}

PointCloudProcessingResult ProcessPointCloud(const PointCloud& input_cloud,
                                             const PointCloudProcessingOptions& options)
{
  ValidateProcessingOptions(options);

  if (input_cloud.empty())
  {
    throw std::invalid_argument("Input point cloud must not be empty.");
  }

  PointCloudProcessingResult result;

  result.input_points = input_cloud.size();

  PointCloud::Ptr current(new PointCloud);

  std::vector<int> valid_indices;

  pcl::removeNaNFromPointCloud(input_cloud, *current, valid_indices);

  result.after_remove_nan = current->size();

  result.after_pass_through = current->size();

  if (options.pass_through.enabled)
  {
    pcl::PassThrough<pcl::PointXYZ> filter;

    filter.setInputCloud(current);

    filter.setFilterFieldName(options.pass_through.axis);

    filter.setFilterLimits(options.pass_through.min_limit, options.pass_through.max_limit);

    PointCloud::Ptr filtered(new PointCloud);

    filter.filter(*filtered);

    current = filtered;

    result.after_pass_through = current->size();
  }

  result.after_statistical_outlier = current->size();

  if (options.statistical_outlier.enabled && !current->empty())
  {
    if (current->size() <= static_cast<std::size_t>(options.statistical_outlier.mean_k))
    {
      throw std::runtime_error(
          "Point cloud is too small for configured StatisticalOutlier mean_k.");
    }

    pcl::StatisticalOutlierRemoval<pcl::PointXYZ> filter;

    filter.setInputCloud(current);

    filter.setMeanK(options.statistical_outlier.mean_k);

    filter.setStddevMulThresh(options.statistical_outlier.stddev_mul);

    PointCloud::Ptr filtered(new PointCloud);

    filter.filter(*filtered);

    current = filtered;

    result.after_statistical_outlier = current->size();
  }

  result.after_voxel_grid = current->size();

  if (options.voxel_grid.enabled && !current->empty())
  {
    pcl::VoxelGrid<pcl::PointXYZ> filter;

    filter.setInputCloud(current);

    filter.setLeafSize(options.voxel_grid.leaf_size, options.voxel_grid.leaf_size,
                       options.voxel_grid.leaf_size);

    PointCloud::Ptr filtered(new PointCloud);

    filter.filter(*filtered);

    current = filtered;

    result.after_voxel_grid = current->size();
  }

  result.cloud = current;

  return result;
}

}  // namespace sl3d